# Generated by Django 5.0.6 on 2024-10-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrClient', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
